#!/bin/sh

set -e

stow -v -d "${PWD}/packages" -t $HOME zsh p10k git tmux sheldon
stow -v -d "${PWD}/packages" -t "${HOME}/.config/" nvim karabiner
stow -v -d "${PWD}/packages" -t "${HOME}/Library/Application Support/Code/User/" vscode
