#!/bin/bash
code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.Bookmarks
code --install-extension blanu.vscode-styled-jsx
code --install-extension bradlc.vscode-tailwindcss
code --install-extension CodeStream.codestream
code --install-extension CraigMaslowski.erb
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension enkia.tokyo-night
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-markdown-todo
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension freebroccolo.reasonml
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension haskell.haskell
code --install-extension hediet.vscode-drawio
code --install-extension HookyQR.beautify
code --install-extension humao.rest-client
code --install-extension justusadam.language-haskell
code --install-extension kimuson.ts-type-expand
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension octref.vetur
code --install-extension Orta.vscode-jest
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension puorc.awesome-vhdl
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension rust-lang.rust
code --install-extension rust-lang.rust-analyzer
code --install-extension satokaz.vscode-memo-life-for-you
code --install-extension sianglim.slim
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension styled-components.vscode-styled-components
code --install-extension stylelint.vscode-stylelint
code --install-extension svelte.svelte-vscode
code --install-extension taichi.vscode-textlint
code --install-extension teabyii.ayu
code --install-extension ulwlu.elly
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscodevim.vim
code --install-extension whtouche.vscode-js-console-utils
code --install-extension wix.vscode-import-cost
code --install-extension zhengxiaoyao0716.intelligence-change-case
code --install-extension zhuangtongfa.material-theme
