tap "andreasgrill/utils"
tap "caskroom/cask"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "mongodb/brew"
tap "rcmdnk/rcmdnkpac"
tap "sanemat/font"
brew "anyenv"
brew "automake"
brew "aws-elasticbeanstalk"
brew "bat"
brew "bluetoothconnector"
brew "brotli"
brew "libpng"
brew "glib"
brew "pkg-config"
brew "cairo"
brew "composer"
brew "coreutils"
brew "openldap"
brew "curl"
brew "deno"
brew "node"
brew "emscripten"
brew "exa"
brew "fd"
brew "giflib"
brew "guile"
brew "unbound"
brew "gnutls"
brew "gobject-introspection"
brew "harfbuzz"
brew "jpeg"
brew "libass"
brew "nghttp2"
brew "srt"
brew "ffmpeg"
brew "pango"
brew "fx"
brew "fzf"
brew "gh"
brew "ghq"
brew "gibo"
brew "git"
brew "git-delta"
brew "git-ftp"
brew "git-secrets"
brew "gnu-time"
brew "go"
brew "google-java-format"
brew "grep"
brew "gron"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "jq"
brew "librsvg"
brew "luajit"
brew "mas"
brew "mycli"
brew "mysql"
brew "neofetch"
brew "tree-sitter", args: ["HEAD"]
brew "neovim"
brew "openjdk@11"
brew "ripgrep"
brew "ruby-build"
brew "rust"
brew "spotify-tui"
brew "stow"
brew "terminal-notifier"
brew "tig"
brew "tldr"
brew "tmux"
brew "translate-shell"
brew "tree"
brew "vim", link: false
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
brew "andreasgrill/utils/auto-selfcontrol"
brew "heroku/brew/heroku"
brew "sanemat/font/ricty"
cask "adobe-creative-cloud", args: { appdir: "/Applications" }
cask "alfred", args: { appdir: "/Applications" }
cask "alt-tab"
cask "appcleaner", args: { appdir: "/Applications" }
cask "background-music"
cask "box-drive"
cask "box-tools"
cask "chromedriver"
cask "clipy"
cask "cyberduck", args: { appdir: "/Applications" }
cask "discord"
cask "diskwave"
cask "docker", args: { appdir: "/Applications" }
cask "evernote"
cask "figma"
cask "flux"
cask "font-fontawesome", args: { appdir: "/Applications" }
cask "font-hack-nerd-font", args: { appdir: "/Applications" }
cask "github"
cask "google-chrome", args: { appdir: "/Applications" }
cask "iterm2"
cask "java11"
cask "kindle", args: { appdir: "/Applications" }
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "ngrok"
cask "notion", args: { appdir: "/Applications" }
cask "obsidian"
cask "postman", args: { appdir: "/Applications" }
cask "rectangle", args: { appdir: "/Applications" }
cask "selfcontrol"
cask "skitch", args: { appdir: "/Applications" }
cask "slack", args: { appdir: "/Applications" }
cask "spotify"
cask "tableplus"
cask "toggl-track"
cask "visual-studio-code"
cask "zoom"
mas "Be Focused", id: 973134470
mas "BetterSnapTool", id: 417375580
mas "CopyClip", id: 595191960
mas "Habitify", id: 1111447047
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "MKPlayer", id: 1335612105
mas "Numbers", id: 409203825
mas "Todoist", id: 585829637
mas "カウントダウンタイマー Countdown Timer", id: 1150771803
