## ----------------------------------------
##	Brewfile
## ----------------------------------------
cask_args appdir: "/Applications"

## ========== Base ==========
brew "fd"
brew "fx"
brew "jq"
brew "bat"
brew "exa"
brew "fzf"
brew "ghq"
brew "git"
brew "hub"
brew 'mas'
brew "vim"
brew "grep"
brew "gron"
brew "tldr"
brew "tmux"
brew "tree"
brew "mycli"
brew "heroku"
brew "neovim"
brew "ffmpeg"
brew "ripgrep"
brew "neofetch"
brew "git-delta"
brew "shellcheck"
brew "git-secrets"

## ========== Shell ==========
brew "zsh"
brew "zsh-completions"

## ========== Language ==========
brew "go"
brew "node"
brew "ruby"
brew "python@3.8"

## ========== Database ==========
brew "mysql"
# brew "redis"
# tap  "mongodb/brew"
# brew "mongodb-community"

## ========== Fonts ==========
tap  "homebrew/cask-fonts"
cask "font-fontawesome"
cask "font-hack-nerd-font"

## ========== Applications ==========
# cask "deepl"
cask "slack"
cask "alfred"
cask "docker"
cask "kindle"
cask "notion"
cask "skitch"
cask "zoomus"
cask "postman"
cask "evernote"
cask "cyberduck"
cask "rectangle"
cask "appcleaner"
cask "google-chrome"
cask "visual-studio-code"
cask "adobe-creative-cloud"
mas  "LINE", id: 539883307
mas  "BetterSnapTool", id: 417375580
